# Generated by Django 4.0.4 on 2022-05-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('StudentID', models.CharField(max_length=11)),
                ('Email', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=11)),
                ('GPA', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Department', models.CharField(choices=[('DS', 'DS'), ('CS', 'CS'), ('IS', 'IS'), ('IT', 'IT'), ('AI', 'AI')], max_length=2)),
                ('level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
