# Generated by Django 4.0.4 on 2022-05-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_student_delete_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='activation',
            field=models.BooleanField(default=False),
        ),
    ]
