# Generated by Django 4.0.4 on 2022-05-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_student_activation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='activation',
        ),
    ]
