# Generated by Django 4.0.4 on 2022-05-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_student_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
